function Hd = IIR_Butter_8th
%IIR_BUTTER_8TH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 05-Aug-2024 19:29:10

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N   = 8;     % Order
Fc1 = 1900;  % First Cutoff Frequency
Fc2 = 2100;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
